sudo: required
language: generic
services: docker
before_install:
- openssl aes-256-cbc -K $encrypted_02d4f5f06f34_key -iv $encrypted_02d4f5f06f34_iv -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d
script:
- docker pull dxjoke/tectonic-docker
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic resume.tex"
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic resume-french.tex"
- curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
  -o dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
- ./dropbox_uploader.sh upload resume.pdf ${TRAVIS_BRANCH}/Nicolas-Badoux-Resume_Latest.pdf
- ./dropbox_uploader.sh upload resume.pdf ${TRAVIS_BRANCH}/Nicolas-Badoux-Resume-v${TRAVIS_BUILD_NUMBER}.pdf
- ./dropbox_uploader.sh upload resume.pdf ${TRAVIS_BRANCH}/Nicolas-Badoux-CV-french_Latest.pdf
- ./dropbox_uploader.sh upload resume.pdf ${TRAVIS_BRANCH}/Nicolas-Badoux-CV-french-v${TRAVIS_BUILD_NUMBER}.pdf
