sudo: required
language: generic
services: docker
before_install:
- openssl aes-256-cbc -K $encrypted_02d4f5f06f34_key -iv $encrypted_02d4f5f06f34_iv
  -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d
script:
- docker pull dxjoke/tectonic-docker
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic resume.tex"
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic resume-french.tex"
- curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
  -o dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
- "./dropbox_uploader.sh upload resume.pdf ${TRAVIS_BRANCH}/Nicolas-Badoux-Resume_Latest.pdf"
- "./dropbox_uploader.sh upload resume.pdf ${TRAVIS_BRANCH}/Nicolas-Badoux-Resume-v${TRAVIS_BUILD_NUMBER}.pdf"
- "./dropbox_uploader.sh upload resume-french.pdf ${TRAVIS_BRANCH}/Nicolas-Badoux-CV-french_Latest.pdf"
- "./dropbox_uploader.sh upload resume-french.pdf ${TRAVIS_BRANCH}/Nicolas-Badoux-CV-french-v${TRAVIS_BUILD_NUMBER}.pdf"
before_deploy:
# Set up git user name and tag this commit
- git config --local user.name "Nicolas Badoux"
- git config --local user.email "n.badoux@hotmail.com"
- git tag "$(date +'Resume-%d-%m-%Y')"
deploy:
  provider: releases
  api_key:
    secure: r6dzwFCzuZ5HHyIxOzFPsKLu+5hJD7nPVv5A5Kxn3GdMIU3Yd93b6356Lm2F1oy4aIiSG6ZPJphuiqywZvcS2mwZxzEFSEEcJ+p3HTlCb9ud4JbeVTla/kjWWh85AjKSVr3zwhVNuVIGJUupEgVlIHZE1/5neg+kFMfhvpTeJ5RQqJZQYhATGxiL22oseG/PyUbzh4oeurlbtj2qpRl+8eDS8cqBbL2RNwTVnndZUCmidpSygaUPZfI7CIO4WayTT+6BPr0lQ+Y3Kd2NGhLG2dCYxCz5t3/yZF8ix+cGIst16VwgA/41stAbNBcRNLQkcON5piZ6bVpeme0T9EZfbFyiQ3dIIq+Dy78S3mGoNLO18NvQuRUzpaP1OmqVHyly5ZmJFpeDkbJNFG2HfGYZ8rs0TnW8tiuPj3kMywKWm5MQuJFP9Fbh37um0kDpqpWwtAspzEM6OYl7b0icV/5HzJE49S6m7PuAoNRGrqaN1mXToyE84MvZf7WTuZA+exM678PzbNFjOYy4ZhCqrTwX+GYh41iFFyt0QG0W65z0KnHCYLhxPNKTxE/N1IpCMrsZXvnbNkuhoy2O6pLhAnEYkuWbHLKQxi2laQk5jmm1QTsIwJO5MIDoeulSlCfL9PnKTm76d8jTuGFWOUgvPjG1VT41C0K+kbWl2md1ZEVCkNg=
  skip_cleanup: true
  file: 
  - resume.pdf
  - resume-french.pdf
  on:
    repo: vwvw/resume
